[package]
name = "tinyFS"
version = "0.1.0"
edition = "2021"

[dependencies]
fuse = "0.3.1"
bincode = "1.3.3"
bitvec = "1"
serde = { version = "1", features = ["derive"] }
time = "0.1"
libc = "0.2.169"
